/*------------------------------------------------------------------------
    File        : SparkSuite
    Syntax      : 
    Author(s)   : dugrau - dugrau@progress.com
    Created     : Thu Aug 20 13:59:39 EDT 2015
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

class SparkSuite: 

    @TestCase(classes="").

end class.