/*------------------------------------------------------------------------
    File        : SampleRealm
    Purpose     :
    Syntax      :
    Description :
    Author(s)   : dugrau
    Created     : Tue Feb 2 15:59:53 EST 2016
    Notes       :
  ----------------------------------------------------------------------*/

using Progress.Lang.* from propath.

class Security.SampleRealm inherits Spark.Core.Security.OEUserRealm final:


end class.