&GLOBAL-DEFINE DATA_PATH C:\BPWork\bpevolution\tools\schema\Sports2kMT\Data\
&GLOBAL-DEFINE TABLE_NAME WebMenu

DEFINE VARIABLE hToken AS HANDLE NO-UNDO.
CREATE CLIENT-PRINCIPAL hToken.
hToken:INITIALIZE("dev", STRING(HEX-ENCODE(GENERATE-UUID))).
hToken:DOMAIN-NAME = "bravepoint_com".
hToken:SEAL("bravepoint").

SECURITY-POLICY:LOAD-DOMAINS("Sports2kMT").
SECURITY-POLICY:SET-CLIENT(hToken).

MESSAGE "UserID: " USERID("Sports2kMT") SKIP
        "Tenant: " TENANT-NAME() VIEW-AS ALERT-BOX.

FOR EACH _Tenant WHERE _Tenant._TenantID GT 0 NO-LOCK:
  DISPLAY _Tenant-Name WITH 1 COL SCROLLABLE.
  SET-EFFECTIVE-TENANT(_Tenant._TenantID).

  FOR EACH {&TABLE_NAME} EXCLUSIVE-LOCK:
    DELETE {&TABLE_NAME}.
  END.

  INPUT FROM {&DATA_PATH}{&TABLE_NAME}.d.
  DISABLE TRIGGERS FOR LOAD OF {&TABLE_NAME}.
  REPEAT:
    CREATE {&TABLE_NAME}.
    IMPORT {&TABLE_NAME}.
  END.
  INPUT CLOSE.
END.

FINALLY:
  hToken:LOGOUT().
  DELETE OBJECT hToken NO-ERROR.
END FINALLY.